import test from 'node:test';
import assert from 'node:assert/strict';
import {proxyAPI,webApp} from './web.mjs';
test('web proxy forwards only protocol headers to the fixed API and streams the body',async()=>{const body=new ReadableStream({start(c){c.enqueue(new TextEncoder().encode('data: hello\n\n'));c.close()}});let target,init;const r=await proxyAPI(new Request('https://impo.ai/api/v1/submissions/123/stream',{headers:{Authorization:'Bearer token',Cookie:'private=secret',Origin:'https://impo.ai'}}),async(u,i)=>{target=u;init=i;return new Response(body,{headers:{'Content-Type':'text/event-stream','Set-Cookie':'bad=value'}})});assert.equal(String(target),'https://mcp.xyznot.com/instant/api/v1/submissions/123/stream');assert.equal(init.headers.get('Cookie'),null);assert.equal(r.headers.get('Set-Cookie'),null);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal(r.body,body);assert.equal(await r.text(),'data: hello\n\n')});
test('web proxy rejects foreign origins and unauthenticated requests',async()=>{const never=()=>{throw new Error('Must not forward')};assert.equal((await proxyAPI(new Request('https://impo.ai/api/v1/profile'),never)).status,401);assert.equal((await proxyAPI(new Request('https://impo.ai/api/v1/account',{method:'DELETE',headers:{Authorization:'Bearer token',Origin:'https://other.example'}}),never)).status,403)});
test('web proxy uses Workers-compatible manual redirects and rejects redirected credentials',async(t)=>{t.mock.method(console,'error',()=>{});let calls=0;const response=await proxyAPI(new Request('https://impo.ai/api/v1/profile',{headers:{Authorization:'Bearer token'}}),async(_url,init)=>{calls++;assert.equal(init.redirect,'manual');return new Response(null,{status:307,headers:{Location:'https://other.example/private'}})});assert.equal(calls,1);assert.equal(response.status,502);assert.equal(response.headers.get('Location'),null);assert.equal((await response.json()).error.code,'upstream_unavailable')});
test('web proxy preserves POST bodies and upstream authentication failures',async()=>{const response=await proxyAPI(new Request('https://impo.ai/api/v1/conversation/messages',{method:'POST',headers:{Authorization:'Bearer token','Content-Type':'application/json'},body:JSON.stringify({text:'Hello',clientMessageId:'message-id'})}),async(_url,init)=>{assert.equal(init.method,'POST');assert.deepEqual(await new Response(init.body).json(),{text:'Hello',clientMessageId:'message-id'});assert.equal(init.headers.get('Authorization'),'Bearer token');return Response.json({error:{code:'unauthorized'}},{status:401,headers:{'X-Request-Id':'upstream-request'}})});assert.equal(response.status,401);assert.equal(response.headers.get('X-Request-Id'),'upstream-request')});
test('deep links serve app HTML while missing assets stay missing',async()=>{const seen=[];const env={ASSETS:{fetch:async r=>{seen.push(new URL(r.url).pathname);return new Response('asset',{status:r.url.endsWith('.js')?404:200})}}};assert.equal((await webApp(new Request('https://impo.ai/app/tasks/123'),env)).status,200);assert.equal((await webApp(new Request('https://impo.ai/app/assets/missing.js'),env)).status,404);assert.deepEqual(seen,['/app/','/app/assets/missing.js']);assert.equal((await webApp(new Request('https://impo.ai/app?x=1'),env)).headers.get('Location'),'https://impo.ai/app/?x=1')});
test('Pages HTML fallback is never returned as a missing JavaScript asset',async()=>{const env={ASSETS:{fetch:async()=>new Response('<html>Homepage</html>',{headers:{'Content-Type':'text/html; charset=utf-8'}})}};const result=await webApp(new Request('https://impo.ai/app/assets/missing.js'),env);assert.equal(result.status,404);assert.equal(result.headers.get('Cache-Control'),'no-store');assert.equal(await result.text(),'Asset not found')});
