-keep class ai.onnxruntime.** { *; }
-keep class org.scilab.forge.jlatexmath.** { *; }
-keepattributes Signature
-keep class com.google.gson.reflect.TypeToken { *; }
-keep class * extends com.google.gson.reflect.TypeToken
